apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
              name: web
          env:
            - name: TEST_ENV
              value: test